# Generated by Django 4.1.2 on 2023-05-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='email',
        ),
    ]
