# Generated by Django 4.1.2 on 2023-05-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_address_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='follow_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
    ]
