# Generated by Django 4.1.2 on 2023-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_follow_author_remove_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='seller_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='seller_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
